### ISSUE TITLE
Will Mortal support service discovery implementations like consul or etcd?

### ISSUE THREAD

**Issue by SgtDaJim** [go-masonry/mortar#10]

**Comment by talgendler** [comment]
@SgtDaJim Mortar defines a [Config Interface](https://github.com/go-masonry/mortar/blob/master/interfaces/cfg/interfaces.go#L52) which in term "implemented" by [**viper**](https://github.com/spf13/viper) using [this](https://github.com/go-masonry/bviper) wrapper. **viper** can be configured to read remote key→value like etcd and Consul. Is this answers your question ?

**Comment by SgtDaJim** [comment]
Eh, not really.
I know there is config file. But I don't find any code of registering to service discovery services.
So I have to implement that myself？
I suggest Mortar can implement  a general service discovery services registration, just like other microservice frameworks.

**Comment by talgendler** [comment]
@SgtDaJim Can you please post a usage example ?
But you probably right, you will have to implement one yourself. One of the main goals was to make mortar as **abstract** as possible.
If you think current Interfaces doesn't cover your usecase I'll be happy to add a new one.

**Comment by SgtDaJim** [comment]
@talgendler Well, apperently now Mortar client have to dial the rpc server directly. But service discovery is a part of microservice, I can conveniently know all my rpc servers with that, no matter how I scale the servers. And general service discovery services includes consul, etcd, edns, etc.

**Comment by SgtDaJim** [comment]
> @SgtDaJim Can you please post a usage example ?
> But you probably right, you will have to implement one yourself. One of the main goals was to make mortar as **abstract** as possible.
> If you think current Interfaces doesn't cover your usecase I'll be happy to add a new one.

I am willing to make a pr if I get spare time ~

**Comment by talgendler** [comment]
@SgtDaJim I'm probably missing something, Mortar doesn't have any special client, the only clients I can think of are `http.Client` and `grpc.ClientConnInterface` both of them accept a target that is similar to `https://somewhere:<port>/path`.
If understand correctly you are asking for a way to get the target of some remote service called `r-service`,but you only know how it's called and not how to access it. In this case you can use viper that is already [wrapped](https://github.com/go-masonry/bviper) to support mortar. [viper have a way](https://github.com/spf13/viper#remote-keyvalue-store-support) to configure remote key→value systems. 

However eventually you should still use [mortar Config Interface](https://github.com/go-masonry/mortar/blob/master/interfaces/cfg/interfaces.go#L52) and get the real target.

```golang
var host = cfg.Get("r-service").String() // viper will do a remote call to Consul to retrieve the actual value, it's not going to be in the files.
```

Another possibility is  to introduce an interceptor and "hijack" the target by querying remote service "on-the-fly".

- `http.Client` [Interceptor](https://github.com/go-masonry/mortar/blob/master/interfaces/http/client/interfaces.go#L21)
```golang
type HTTPClientInterceptor func(*http.Request, HTTPHandler) (*http.Response, error)
```
- `grpc. UnaryClientInterceptor` [Interceptor](https://github.com/grpc/grpc-go/blob/master/interceptor.go#L43)
```golang
type UnaryClientInterceptor func(ctx context.Context, method string, req, reply interface{}, cc *ClientConn, invoker UnaryInvoker, opts ...CallOption) error
```
